CREATE TABLE [oak].[StockDyn] (
    [StockDynID]     INT             IDENTITY (1, 1) NOT NULL,
    [PrdGrp]         NVARCHAR (10)   NULL,
    [Catagory]       NVARCHAR (10)   NULL,
    [Section]        NVARCHAR (10)   NULL,
    [Profile]        NVARCHAR (10)   NULL,
    [Rim]            NVARCHAR (10)   NULL,
    [Speed]          NVARCHAR (5)    NULL,
    [Constru]        NVARCHAR (10)   NULL,
    [Ply]            INT             NULL,
    [TreadPat]       NVARCHAR (100)  NULL,
    [LoadIx]         NVARCHAR (10)   NULL,
    [Direct]         BIT             NULL,
    [Asymm]          BIT             NULL,
    [Hand]           BIT             NULL,
    [RunFlat]        BIT             NULL,
    [ExLoad]         BIT             NULL,
    [Remould]        BIT             NULL,
    [ThreePeaks]     BIT             NULL,
    [IceGrip]        BIT             NULL,
    [SpSaver]        BIT             NULL,
    [TyClass]        NVARCHAR (10)   NULL,
    [TyFuelC]        NVARCHAR (5)    NULL,
    [TyWGC]          NVARCHAR (5)    NULL,
    [TyRRC]          NVARCHAR (5)    NULL,
    [TyWetGrip]      NVARCHAR (5)    NULL,
    [TyNoiseDB]      NVARCHAR (5)    NULL,
    [TyNoise]        NVARCHAR (5)    NULL,
    [TyAccredit]     NVARCHAR (50)   NULL,
    [TyEprelId]      NVARCHAR (50)   NULL,
    [DescripN]       NVARCHAR (200)  NULL,
    [Depot]          INT             NULL,
    [StockBal]       DECIMAL (18, 2) NULL,
    [InWorkshop]     DECIMAL (18, 2) NULL,
    [InTransitTo]    DECIMAL (18, 2) NULL,
    [InTransitFrom]  DECIMAL (18, 2) NULL,
    [InTransitVan]   DECIMAL (18, 2) NULL,
    [OnOrder]        DECIMAL (18, 2) NULL,
    [BackOrder]      DECIMAL (18, 2) NULL,
    [LongTerm]       DECIMAL (18, 2) NULL,
    [ReordMin]       DECIMAL (18, 2) NULL,
    [ReordNorm]      DECIMAL (18, 2) NULL,
    [ReordMax]       DECIMAL (18, 2) NULL,
    [ReordBulk]      DECIMAL (18, 2) NULL,
    [StdCost]        DECIMAL (18, 2) NULL,
    [Prices1]        DECIMAL (18, 2) NULL,
    [Prices2]        DECIMAL (18, 2) NULL,
    [Prices3]        DECIMAL (18, 2) NULL,
    [Prices4]        DECIMAL (18, 2) NULL,
    [Prices5]        DECIMAL (18, 2) NULL,
    [Prices6]        DECIMAL (18, 2) NULL,
    [Prices7]        DECIMAL (18, 2) NULL,
    [Prices8]        DECIMAL (18, 2) NULL,
    [SdRecord]       INT             NULL,
    [StockID]        INT             NULL,
    [ManufacturerID] INT             NULL,
    CONSTRAINT [PK_StockDyn] PRIMARY KEY CLUSTERED ([StockDynID] ASC),
    CONSTRAINT [FK_StockDyn_ManufacturerID] FOREIGN KEY ([ManufacturerID]) REFERENCES [oak].[Manufacturer] ([ManufacturerID]),
    CONSTRAINT [FK_StockDyn_Stock] FOREIGN KEY ([StockID]) REFERENCES [oak].[Stock] ([StockID])
);


GO
CREATE NONCLUSTERED INDEX [IX_StockDyn_StockID_StockBal]
    ON [oak].[StockDyn]([StockID] ASC)
    INCLUDE([StockBal]);

