CREATE TABLE [oak].[Stock] (
    [StockID]        INT             IDENTITY (1, 1) NOT NULL,
    [StRecord]       INT             NOT NULL,
    [StCode]         NVARCHAR (50)   NULL,
    [StBarCode]      NVARCHAR (50)   NULL,
    [StKType]        NVARCHAR (5)    NULL,
    [Descripn]       NVARCHAR (100)  NULL,
    [Longdesc]       NVARCHAR (200)  NULL,
    [Prdgrp]         NVARCHAR (10)   NULL,
    [OEList]         NVARCHAR (50)   NULL,
    [Origin]         NVARCHAR (20)   NULL,
    [Static01]       INT             NULL,
    [Static02]       INT             NULL,
    [Static03]       INT             NULL,
    [Static04]       INT             NULL,
    [Static05]       INT             NULL,
    [Static06]       INT             NULL,
    [Static07]       DECIMAL (10, 2) NULL,
    [Static08]       DECIMAL (10, 2) NULL,
    [Static09]       INT             NULL,
    [Static10]       INT             NULL,
    [Section]        NVARCHAR (10)   NULL,
    [Profile]        NVARCHAR (10)   NULL,
    [Rim]            NVARCHAR (10)   NULL,
    [Speed]          NVARCHAR (5)    NULL,
    [Constru]        NVARCHAR (10)   NULL,
    [Ply]            NVARCHAR (10)   NULL,
    [Treadpat]       NVARCHAR (100)  NULL,
    [Loadix]         NVARCHAR (10)   NULL,
    [Direct]         BIT             NULL,
    [Asymm]          BIT             NULL,
    [Hand]           BIT             NULL,
    [Runflat]        BIT             NULL,
    [EXLoad]         BIT             NULL,
    [TYSeason]       NVARCHAR (5)    NULL,
    [Threepeaks]     BIT             NULL,
    [Icegrip]        BIT             NULL,
    [Spsaver]        BIT             NULL,
    [Demount]        BIT             NULL,
    [Selfseal]       BIT             NULL,
    [Heavyload]      BIT             NULL,
    [Lowroll]        BIT             NULL,
    [Noisedamp]      BIT             NULL,
    [Ev]             BIT             NULL,
    [TyClass]        NVARCHAR (10)   NULL,
    [TyFuelc]        NVARCHAR (5)    NULL,
    [TyWgc]          NVARCHAR (5)    NULL,
    [TyRrc]          NVARCHAR (5)    NULL,
    [TyWetgrip]      NVARCHAR (5)    NULL,
    [TyNoisedb]      NVARCHAR (5)    NULL,
    [TyNoise]        NVARCHAR (5)    NULL,
    [TyTread]        NVARCHAR (100)  NULL,
    [ManufacturerID] INT             NULL,
    CONSTRAINT [PK_Stock] PRIMARY KEY CLUSTERED ([StockID] ASC),
    CONSTRAINT [FK_Stock_ManufacturerID] FOREIGN KEY ([ManufacturerID]) REFERENCES [oak].[Manufacturer] ([ManufacturerID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_Stock_StCode]
    ON [oak].[Stock]([StCode] ASC);

